<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Masukan aksesibilitas_jfN4p</name>
   <tag></tag>
   <elementGuidId>3e706f5f-98f7-45d7-9b61-cfbfe5417e66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.jfN4p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='logo']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>921e9382-fbe3-43b5-8b8b-a5e69c8bfb06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jfN4p</value>
      <webElementGuid>b7a6c20f-8312-474a-9642-36ef2cf5081d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png</value>
      <webElementGuid>5efd4411-1e38-4673-a36d-c54639397f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Google</value>
      <webElementGuid>c680e96a-466d-4d32-bf1e-48eaf3e04b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>26548351-4360-4a66-b36d-eec747d78857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>92</value>
      <webElementGuid>a2186b02-74c2-4598-a61d-a65f3039a390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csiid</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>301e2a49-5d0a-4f38-bd17-eaa1e5ccf163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-atf</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fcfd264a-3033-4ea9-96cc-b4742341c751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo&quot;)/img[@class=&quot;jfN4p&quot;]</value>
      <webElementGuid>827639d6-8a71-4071-87f1-1b6816c1e2e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='logo']/img</value>
      <webElementGuid>a8d612ff-8cb1-4d5d-81ab-943ef7b7562b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Google']</value>
      <webElementGuid>1be4a32a-8dbf-44a9-aff0-e86fee2cac70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>405515b6-d89f-4936-a19b-4993dfc2d3b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png' and @alt = 'Google']</value>
      <webElementGuid>5b9af6eb-2bee-4d36-8593-bf4edfe46450</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
